// Copyright 2024 Normal Browser Authors. All rights reserved.
// ghost_mode_jni_bridge.cc — JNI bridge between Java GhostModeManager
//                             and C++ DeviceProfileStore.
//
// FILE: chrome/android/native/ghost_mode_jni_bridge.cc
//
// This file implements the native methods declared in
// GhostModeManager.java @NativeMethods interface.

#include "base/android/jni_android.h"
#include "base/android/jni_string.h"
#include "base/android/context_utils.h"
#include "base/json/json_writer.h"
#include "base/task/thread_pool.h"
#include "content/public/browser/browser_context.h"
#include "content/public/browser/browser_thread.h"
#include "content/public/browser/render_frame_host.h"
#include "content/public/browser/render_process_host.h"
#include "content/public/browser/storage_partition.h"
#include "content/public/browser/web_contents.h"
#include "chrome/browser/profiles/profile_manager.h"
#include "device_profile_generator/profile_store.h"
#include "net/dns/host_resolver.h"

// Auto-generated JNI header (generated by Chromium's JNI generator)
// #include "chrome/android/jni_headers/GhostModeManager_jni.h"

using base::android::ConvertUTF8ToJavaString;
using base::android::JavaParamRef;
using base::android::ScopedJavaLocalRef;

namespace normal_browser {

// ====================================================================
// nativeSetGhostModeActive — Enable/disable Ghost Mode
// ====================================================================
static void JNI_GhostModeManager_NativeSetGhostModeActive(
    JNIEnv* env,
    jboolean active) {
  DeviceProfileStore::Get()->SetGhostModeActive(active);
}

// ====================================================================
// nativeGenerateNewProfile — Generate completely new device identity
// ====================================================================
static void JNI_GhostModeManager_NativeGenerateNewProfile(
    JNIEnv* env) {
  DeviceProfileStore::Get()->GenerateNewProfile();
}

// ====================================================================
// nativeGetProfileJson — Get current profile as JSON string
// ====================================================================
static ScopedJavaLocalRef<jstring>
JNI_GhostModeManager_NativeGetProfileJson(
    JNIEnv* env) {
  auto& profile = DeviceProfileStore::Get()->GetProfile();
  std::string json = profile.ToJSON();
  return ConvertUTF8ToJavaString(env, json);
}

// ====================================================================
// nativeNotifyProfileChanged — Notify all renderers of profile change
// ====================================================================
static void JNI_GhostModeManager_NativeNotifyProfileChanged(
    JNIEnv* env) {
  // Notify all active renderer processes to re-fetch the GhostProfile.
  // We iterate all RenderProcessHosts — each hosts one or more renderers
  // that cache the profile via GhostProfileClient.
  //
  // Each renderer's GhostProfileClient subscribed to the
  // GhostProfileProvider Mojo interface on startup. Sending a
  // re-initialization signal causes them to re-request the profile.
  //
  // Simplest correct approach: terminate and restart all renderer
  // processes. This forces re-initialization of GhostProfileClient
  // in each new renderer, picking up the latest profile.
  for (auto iter = content::RenderProcessHost::AllHostsIterator();
       !iter.IsAtEnd(); iter.Advance()) {
    content::RenderProcessHost* host = iter.GetCurrentValue();
    if (host && host->IsInitializedAndNotDead()) {
      // Fast shutdown triggers renderer restart on next navigation.
      // The renderer will re-fetch the profile via Mojo on startup.
      host->FastShutdownIfPossible(/* page_count= */ 0,
                                    /* skip_unload_handlers= */ true);
    }
  }
}

// ====================================================================
// nativeRotateSessionSeeds — Keep device, change fingerprint seeds
// ====================================================================
static void JNI_GhostModeManager_NativeRotateSessionSeeds(
    JNIEnv* env) {
  DeviceProfileStore::Get()->RotateSession();
}

// ====================================================================
// nativeImportProfileJson — Import a profile from JSON string
// ====================================================================
static void JNI_GhostModeManager_NativeImportProfileJson(
    JNIEnv* env,
    const JavaParamRef<jstring>& json_jstr) {
  std::string json = ConvertJavaStringToUTF8(env, json_jstr);
  if (json.empty()) return;

  DeviceProfile imported = DeviceProfile::FromJSON(json);
  // Check if parse succeeded (manufacturer_name will be non-empty for valid profiles)
  if (!imported.manufacturer_name.empty()) {
    DeviceProfileStore::Get()->SetProfile(std::move(imported));
  }
}

// ====================================================================
// nativeClearWebStorage — Clear localStorage, IndexedDB, WebSQL, FileSystems
// ====================================================================
static void JNI_GhostModeManager_NativeClearWebStorage(
    JNIEnv* env) {
  content::BrowserContext* browser_context =
      ProfileManager::GetLastUsedProfile();
  if (!browser_context) return;

  content::StoragePartition* partition =
      browser_context->GetDefaultStoragePartition();
  if (!partition) return;

  // Clear all web storage types
  uint32_t remove_mask =
      content::StoragePartition::REMOVE_DATA_MASK_LOCAL_STORAGE |
      content::StoragePartition::REMOVE_DATA_MASK_INDEXEDDB |
      content::StoragePartition::REMOVE_DATA_MASK_WEBSQL |
      content::StoragePartition::REMOVE_DATA_MASK_FILE_SYSTEMS |
      content::StoragePartition::REMOVE_DATA_MASK_SHADER_CACHE |
      content::StoragePartition::REMOVE_DATA_MASK_CACHE_STORAGE;

  partition->ClearData(
      remove_mask,
      content::StoragePartition::QUOTA_MANAGED_STORAGE_MASK_ALL,
      content::StoragePartition::OriginMatcherFunction(),
      nullptr,  // cookie_deletion_filter
      true,     // perform_storage_cleanup
      base::Time(),
      base::Time::Max(),
      base::DoNothing());
}

// ====================================================================
// nativeClearHttpCache — Clear disk and memory HTTP cache + DNS cache
// ====================================================================
static void JNI_GhostModeManager_NativeClearHttpCache(
    JNIEnv* env) {
  content::BrowserContext* browser_context =
      ProfileManager::GetLastUsedProfile();
  if (!browser_context) return;

  auto* partition = browser_context->GetDefaultStoragePartition();
  if (!partition) return;

  // Clear HTTP cache
  partition->GetNetworkContext()->ClearHttpCache(
      base::Time(), base::Time::Max(),
      nullptr,  // filter
      base::DoNothing());

  // Clear DNS cache
  partition->GetNetworkContext()->ClearHostCache(
      nullptr,  // filter
      base::DoNothing());

  // Close idle sockets to prevent connection reuse tracking
  partition->GetNetworkContext()->CloseIdleConnections(
      base::DoNothing());

  // Clear HSTS state for all hosts
  partition->GetNetworkContext()->DeleteDynamicDataForHost(
      "*", base::DoNothing());
}

// ====================================================================
// nativeClearServiceWorkers — Unregister all service workers
// ====================================================================
static void JNI_GhostModeManager_NativeClearServiceWorkers(
    JNIEnv* env) {
  content::BrowserContext* browser_context =
      ProfileManager::GetLastUsedProfile();
  if (!browser_context) return;

  auto* partition = browser_context->GetDefaultStoragePartition();
  if (!partition) return;

  // Delete all service workers and their caches
  partition->GetServiceWorkerContext()->DeleteAndStartOver(
      base::DoNothing());

  // Also clear Cache Storage (SW caches)
  partition->ClearData(
      content::StoragePartition::REMOVE_DATA_MASK_CACHE_STORAGE,
      content::StoragePartition::QUOTA_MANAGED_STORAGE_MASK_ALL,
      content::StoragePartition::OriginMatcherFunction(),
      nullptr, true, base::Time(), base::Time::Max(),
      base::DoNothing());
}

// ====================================================================
// Profile loading from SharedPreferences on startup
// Called from DeviceProfileStore constructor
// ====================================================================
bool LoadProfileFromJavaStorage(DeviceProfile* out_profile) {
  JNIEnv* env = base::android::AttachCurrentThread();
  if (!env) return false;

  // Get the application context
  auto context = base::android::GetApplicationContext();

  // Check if stored profile exists via SharedPreferences
  base::android::ScopedJavaLocalRef<jclass> clazz =
      base::android::GetClass(env, "org/nicegram/browser/GhostModeManager");
  jmethodID has_method = env->GetStaticMethodID(
      clazz.obj(), "hasStoredProfile", "(Landroid/content/Context;)Z");
  if (!has_method) return false;
  jboolean has = env->CallStaticBooleanMethod(clazz.obj(), has_method,
                                               context.obj());
  if (!has) return false;

  // Get stored JSON string
  jmethodID get_method = env->GetStaticMethodID(
      clazz.obj(), "getStoredProfileJson",
      "(Landroid/content/Context;)Ljava/lang/String;");
  if (!get_method) return false;
  base::android::ScopedJavaLocalRef<jstring> json_jstr(
      env,
      static_cast<jstring>(env->CallStaticObjectMethod(
          clazz.obj(), get_method, context.obj())));
  if (!json_jstr) return false;

  std::string json = base::android::ConvertJavaStringToUTF8(env, json_jstr);
  if (json.empty()) return false;

  // Parse JSON → DeviceProfile
  DeviceProfile parsed = DeviceProfile::FromJSON(json);
  if (parsed.manufacturer_name.empty()) return false;
  *out_profile = std::move(parsed);
  return true;
}

}  // namespace normal_browser
